### ISSUE TITLE
Unable to import sample-geo.json

### ISSUE THREAD

**Issue by tonymarsh** [yvesonline/saved-places-importer#1]
Hi,
Following your example, I get the below when I try to import sample-geo.json

`(venv) bash-5.0$ python spi.py batch --dry-run ./samples/sample-geo.json
Traceback (most recent call last):
  File "spi.py", line 369, in <module>
    spi = SavedPlacesImporter(args)
  File "spi.py", line 64, in __init__
    data = json.load(f)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 6 - line 2 column 1 (char 5 - 48)
`
Please let me know if you need any additional info.

**Comment by tonymarsh** [comment]
Seems to be Big Sur related. closing.
